# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# PRs to main
pr:
- main

trigger:
- main

jobs:
- job: SecretsCheck

pool:
  vmImage: ubuntu-latest

  steps:

  - script: |
      # Set up CURL headers + URI
      headers="Authorization: Bearer $(System.AccessToken)"
       uri="$(System.TeamFoundationServerUri)$(System.TeamProject)/_apis/build/builds/$(Build.BuildId)/changes"
      
      # Set count of changes in this Push to the ChangesCount variable
      ChangesCount=$(echo $(curl -sSL -H "$headers" "$uri") | jq '.count')

      # If PR, add 1 to ChangesCount.
      if [ "$(Build.Reason)" == "PullRequest" ]; then ChangesCount=$(($ChangesCount+1)); fi

      # Export ChangesCount variable for use in other steps
      echo "##vso[task.setvariable variable=ChangesCount]$(echo $ChangesCount )"