name: AktoScan
on:
  push

jobs:
  ApiTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run CI/CD tests
      uses: akto-api-security/run-scan@v1.0.3
      with:
        AKTO_DASHBOARD_URL: ${{secrets.AKTO_DASHBOARD_URL}}
        AKTO_API_KEY: ${{secrets.AKTO_API_KEY}}
        AKTO_TEST_ID: ${{secrets.AKTO_TEST_ID}} 
      # run: |
      #       curl ${{secrets.AKTO_DASHBOARD_URL}}+"/api/startTest" \
      #       -H 'X-API-KEY: ${{secrets.AKTO_API_KEY}}' \
      #       -H 'content-type: application/json' \
      #       -d '{"testingRunHexId": ${{secrets.AKTO_TEST_ID}}, "startTimestamp" : 0,"metadata": {"platform": "Github Actions"}}' \
      #       --compressed
